Repository Solobrosco/monitor-bot, pull requests merged in 2021-01, with the labels that each got.

#8 Updated README.md
  README.md
Labels: enhancement

#12 Requirements
  README.md
  notes.txt
  requirements.txt
Labels: documentation, enhancement

#13 added user-input plus more accurate url to be returned
  main.py
Labels: enhancement

#14 Updated requirements.txt
  requirements.txt
Labels: documentation
